export const roomData = [
  {
    id: 0,
    korName: '스탠다드 원룸',
    enName: 'One Room Standard',
    rooms: [
      {
        id: 0,
        korName: '원룸 스탠다드 더블 마운틴',
        enName: 'One Room Standard Double Mountain',
        size: '전용면적 24.79㎡ / 분양면적 47.88㎡',
        default: 2,
        max: 3,
        desc: '설악산을 바라보며 한결 가벼워진 마음으로 실속을 중시하는 고객을 위한 컴팩트한 1Room 객실',
        roomType: '침실1, 욕실1',
        bedType: '더블1',
        imgNum: 3,
      },
      {
        id: 1,
        korName: '원룸 스탠다드 더블 오션',
        enName: 'One Room Standard Double Ocean',
        size: '전용면적 26.33㎡ / 분양면적 50.78㎡',
        default: 2,
        max: 3,
        desc: '바다 위로 쏟아지는 햇살에 반짝이는 바다. 그 아름다운 장관을 만날 수 있는 1Room 객실',
        roomType: '침실1, 욕실1',
        bedType: '더블1',
        imgNum: 6,
      },
      {
        id: 2,
        korName: '원룸 스탠다드 트윈 마운틴',
        enName: 'One Room Standard Twin Mountain',
        size: '전용면적 32.35㎡ / 분양면적 62.39㎡',
        default: 3,
        max: 3,
        desc: '차분한 분위기의 편안하고 여유로운 시간을 보내실 수 있는 1Room객실',
        roomType: '침실1, 욕실1',
        bedType: '더블1, 싱글1',
        imgNum: 6,
      },
      {
        id: 3,
        korName: '원룸 스탠다드 트윈 하프오션',
        enName: 'One Room Standard Twin Half-ocean',
        size: '전용면적 32.35㎡ / 분양면적 62.39㎡',
        default: 3,
        max: 3,
        desc: '차분한 분위기의 편안하고 여유로운 시간을 보내실 수 있는 1Room객실',
        roomType: '침실1, 욕실1',
        bedType: '더블1, 싱글1',
        imgNum: 6,
      },
    ],
  },
  {
    id: 1,
    korName: '슈페리어 투룸',
    enName: 'Two Room Superior',
    rooms: [
      {
        id: 0,
        korName: '투룸 슈페리어 더블',
        enName: 'Two Room Superior Double',
        size: '전용면적 68.74㎡ / 분양면적 92.15㎡',
        default: 4,
        max: 4,
        desc: '가족들과 함께 낙산의 정취를 즐기기에 충분한 2Room 타입 객실',
        roomType: '침실2, 욕실1',
        bedType: '더블2',
        imgNum: 7,
      },
      {
        id: 1,
        korName: '투룸 슈페리어 코너',
        enName: 'Two Room Superior Corner',
        size: '전용면적 71.39㎡ / 분양면적 95.70㎡',
        default: 4,
        max: 5,
        desc: '바다를 항해하는 듯한 꿈 같은 휴식이 있는 2Room 객실',
        roomType: '침실2, 욕실1',
        bedType: '더블1, 온돌1',
        imgNum: 10,
      },
      {
        id: 2,
        korName: '투룸 슈페리어 패밀리',
        enName: 'Two Room Superior Family',
        size: '전용면적 72.97㎡ / 분양면적 97.82㎡',
        default: 4,
        max: 5,
        desc: '바다를 항해하는 듯한 꿈 같은 휴식이 있는 2Room 객실',
        roomType: '침실2, 욕실1',
        bedType: '더블1, 온돌1',
        imgNum: 7,
      },
    ],
  },
  {
    id: 2,
    korName: '디럭스 투룸',
    enName: 'Two Room Deluxe',
    rooms: [
      {
        id: 0,
        korName: '투룸 디럭스 패밀리',
        enName: 'Two Room Deluxe Family',
        size: '전용면적 90.24㎡ / 분양면적 120.99㎡',
        default: 4,
        max: 5,
        desc: '가족단위 여행자를 위한 객실로 4인 가족이 즐기기에 충분한 2Room 타입 객실',
        roomType: '침실2, 욕실2',
        bedType: '더블1, 온돌1',
        imgNum: 11,
      },
    ],
  },
  {
    id: 3,
    korName: '펜트하우스',
    enName: 'Pent House',
    rooms: [
      {
        id: 0,
        korName: '쓰리룸 펜트하우스',
        enName: 'Three Room Pent House',
        size: '전용면적 98.67㎡ / 분양면적 132.27㎡',
        default: 6,
        max: 7,
        desc: '지친 삶 속에 자연을 느낄 수 있도록 산과 바다가 있는 휴식을 선사하는 펜트하우스',
        roomType: '침실3, 욕실2',
        bedType: '더블2, 온돌1',
        imgNum: 9,
      },
    ],
  },
];
